name: build and deploy

on:
  push:
    branches:
      - master

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/tests:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Login to Github package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
      - name: Build docker image
        run: docker build -t ${IMAGE} .
      - name: Push docker image
        run: docker push ${IMAGE}

#  tag:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#    - uses: actions/checkout@master
#    - name: Set tag to trigger jenkins job
#      uses: anothrNick/github-tag-action@master
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

