name: build and deploy

on:
  push:
    branches:
      - master

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/tests:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Login to Github package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
      - name: Build docker image
        run: docker build -t ${IMAGE} .
      - name: Push docker image
        run: docker push ${IMAGE}

  merge-with-release-branch:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Merge with release branch
      uses: devmasx/merge-branch@v1.1.0
      with:
        type: now
        target_branch: 'release'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
